### ISSUE TITLE
编译和启动报同错误！！

### ISSUE THREAD

**Issue by jlintxia** [EasilyTest/stf#1]
![image](https://user-images.githubusercontent.com/28779574/106411638-add5e600-6480-11eb-9569-3939e2080217.png)

**Comment by EasilyTest** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/28779574/106411638-add5e600-6480-11eb-9569-3939e2080217.png)

能贴个log出来吗，图片加载不出来，系统版本和node版本是多少

**Comment by jlintxia** [comment]
问题已解决，是我依赖库没下全

**Comment by JaminZhang** [comment]
> 问题已解决，是我依赖库没下全

遇到差不多的报错，请问哪些依赖没下全啊？怎么重新下载？
本人小白。。。
