### ISSUE TITLE
请问mac端是用node的什么版本编译的，另外，想私聊作者，寻求合作

### ISSUE THREAD

**Issue by carozhu** [EasilyTest/stf#10]
**What is the issue or idea you have?**

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

**Please provide the steps to reproduce the issue.**

**What is the expected behavior?**

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

**Please run `stf doctor` and paste the output here.**

**Comment by KorsChen** [comment]
node8

**Comment by carozhu** [comment]
我用的是v8.17.0. 
方便加你QQ私聊请教吗？谢谢

**Comment by EasilyTest** [comment]
> 我用的是v8.17.0.
> 方便加你QQ私聊请教吗？谢谢

Mac端我用的是8.9，你可以降级试试或者通过 npm install n  来管理版本

**Comment by carozhu** [comment]
谢谢，我试试
