### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: _zmq_version   

### ISSUE THREAD

**Issue by unkangfutable** [EasilyTest/stf#19]
node 8.9.1 npm 5.5.1 mac 系统11.1
在stf 目录下 cnpm insatll   完成依赖安装后，使用stf doctor 命令查看环境，报错
dyld: lazy symbol binding failed: Symbol not found: _zmq_version  
Referenced from: /Users/ly/de/ti/stf/node_modules/_zmq@2.15.3@zmq/build/Release/zmq.node   
Expected in: flat namespace

![QQ图片20210625163919](https://user-images.githubusercontent.com/49712805/123396788-4f96d480-d5d4-11eb-9ee9-22826e42cb0f.png)

**Comment by unkangfutable** [comment]
node  8.9.1 npm 5.5.1  mac 系统11.1

**Comment by xiaohuanxiong3** [comment]
试一下这条命令可不可以 export PKG_CONFIG_PATH=/opt/homebrew/Cellar/zeromq/4.3.4/lib/pkgconfig/，
我遇到了同样的问题，运行这条命令后stf doctor检测zmq就没问题了

**Comment by looowoool** [comment]
> 

我的是mac m1芯片  版本11.6  。export PKG_CONFIG_PATH=/opt/homebrew/Cellar/zeromq/4.3.4/lib/p运行这个并不可以，还有什么好办法么？

**Comment by looowoool** [comment]
弄了一天，安装x86版本honebrew后可解决这个问题
