### ISSUE TITLE
如果想直接在bin目录下./stf启动的话，需要先chmod +x stf

### ISSUE THREAD

**Issue by lin54241930** [EasilyTest/stf#2]
我就不提pr了，大佬改一下吧，要是能吧画质调整改出来的话，就更好了，感谢大佬开源

**Comment by EasilyTest** [comment]
> 
> 
> 我就不提pr了，大佬改一下吧，要是能吧画质调整改出来的话，就更好了，感谢大佬开源

好的，感谢。
画质调节会在下个版本里放出来
