### ISSUE TITLE
编译提示鉴权失败

### ISSUE THREAD

**Issue by dashixiong1018** [EasilyTest/stf#4]
现象：
![image](https://user-images.githubusercontent.com/25193637/114301147-fef3fd00-9af5-11eb-8b13-d1e00cd540ff.png)

ng-context-menu已被作者移除或设置为私有仓库。
官方issue链接：https://github.com/DeviceFarmer/stf/issues/219

openstf已被遗弃，转到DeviceFarmer

**Comment by EasilyTest** [comment]
> 现象：
> ![image](https://user-images.githubusercontent.com/25193637/114301147-fef3fd00-9af5-11eb-8b13-d1e00cd540ff.png)
> 
> ng-context-menu已被作者移除或设置为私有仓库。
> 官方issue链接：[DeviceFarmer/stf#219](https://github.com/DeviceFarmer/stf/issues/219)
> 
> openstf已被遗弃，转到DeviceFarmer

已修改bower.json
