### ISSUE TITLE
Linux(centos)的环境搭建是在宿主机上装还是容器里面呢？

### ISSUE THREAD

**Issue by jeniva** [EasilyTest/stf#6]
目前我可以在容器里面使用tidevice跑ios的自动化了，现在想Linux上的stf上能查看ios的手机，这样怎么做呢？

**Comment by EasilyTest** [comment]
在容器里编译安装即可，但是现在的版本有bug待修复

**Comment by jeniva** [comment]
啥bug，按照README.md里面的安装步骤可以安装成功吗？容器里面怎么启动stf和宿主机上起的Android的stf同时展示呢？
