### ISSUE TITLE
编译libimobiledevice时出错

### ISSUE THREAD

**Issue by YellowShy** [EasilyTest/stf#7]
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking whether gcc and cc understand -c and -o together... yes
./configure: line 4594: AC_PROG_LIBTOOL: command not found
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for libusbmuxd... no
configure: error: Package requirements (libusbmuxd-2.0 >= 2.0.2) were not met:

No package 'libusbmuxd-2.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables libusbmuxd_CFLAGS
and libusbmuxd_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

**Comment by zealotZB** [comment]
他的命令很多都有问题，哎 好多坑啊   拉去libimobiledevice后 没有Makefile 怎么编译啊

**Comment by EasilyTest** [comment]
> checking for gcc option to accept ISO C89... none needed
> checking for style of include used by make... GNU
> checking dependency style of gcc... gcc3
> checking for g++... g++
> checking whether we are using the GNU C++ compiler... yes
> checking whether g++ accepts -g... yes
> checking dependency style of g++... gcc3
> checking whether gcc and cc understand -c and -o together... yes
> ./configure: line 4594: AC_PROG_LIBTOOL: command not found
> checking for pkg-config... /usr/bin/pkg-config
> checking pkg-config is at least version 0.9.0... yes
> checking for libusbmuxd... no
> configure: error: Package requirements (libusbmuxd-2.0 >= 2.0.2) were not met:
> 
> No package 'libusbmuxd-2.0' found
> 
> Consider adjusting the PKG_CONFIG_PATH environment variable if you
> installed software in a non-standard prefix.
> 
> Alternatively, you may set the environment variables libusbmuxd_CFLAGS
> and libusbmuxd_LIBS to avoid the need to call pkg-config.
> See the pkg-config man page for more details.

从报错来看应该是是libusbmuxd没有安装，需要编译安装libusbmuxd-2.0

**Comment by EasilyTest** [comment]
> 他的命令很多都有问题，哎 好多坑啊 拉去libimobiledevice后 没有Makefile 怎么编译啊

libimobiledevice只是提供了安装思路，因为是第三方库安装的过程和操作都会有所变动，需要灵活去编译
